var data = [
  { 'Functional Group': 'Long-term Transport', 'Class': 'Local Mono Fine', 'Magnitude': 2 },
  { 'Functional Group': 'Long-term Transport', 'Class': 'Local Mono Coarse', 'Magnitude': 5 },
  { 'Functional Group': 'Long-term Transport', 'Class': 'Local Matt Painted', 'Magnitude': 1 },
  { 'Functional Group': 'Long-term Transport', 'Class': 'Local Impressed/Incised', 'Magnitude': 0 },
  { 'Functional Group': 'Long-term Transport', 'Class': 'Local Black Glazed', 'Magnitude': 0 },
  { 'Functional Group': 'Long-term Transport', 'Class': 'Regional Mono Fine', 'Magnitude': 0 },
  { 'Functional Group': 'Long-term Transport', 'Class': 'Regional Mono Coarse', 'Magnitude': 3 },
  { 'Functional Group': 'Long-term Transport', 'Class': 'Regional Matt Painted', 'Magnitude': 0 },
  { 'Functional Group': 'Long-term Transport', 'Class': 'Regional Impressed/Incised', 'Magnitude': 3 },
  { 'Functional Group': 'Long-term Transport', 'Class': 'Regional Black Glazed', 'Magnitude': 0 },
  { 'Functional Group': 'Long-term Transport', 'Class': 'Local/Regional Mono Fine', 'Magnitude': 1 },
  { 'Functional Group': 'Long-term Transport', 'Class': 'Local/Regional Mono Coarse', 'Magnitude': 3 },
  { 'Functional Group': 'Long-term Transport', 'Class': 'Local/Regional Matt Painted', 'Magnitude': 0 },
  { 'Functional Group': 'Long-term Transport', 'Class': 'Local/Regional Impressed/Incised', 'Magnitude': 0 },
  { 'Functional Group': 'Long-term Transport', 'Class': 'Local/Regional Black Glazed', 'Magnitude': 0 },
  { 'Functional Group': 'Long-term Transport', 'Class': 'Import Mono Fine', 'Magnitude': 9 },
  { 'Functional Group': 'Long-term Transport', 'Class': 'Import Mono Coarse', 'Magnitude': 3 },
  { 'Functional Group': 'Long-term Transport', 'Class': 'Import Matt Painted', 'Magnitude': 0 },
  { 'Functional Group': 'Long-term Transport', 'Class': 'Import Impressed/Incised', 'Magnitude': 0 },
  { 'Functional Group': 'Long-term Transport', 'Class': 'Import Black Glazed', 'Magnitude': 0 },
  { 'Functional Group': 'Long-term Transport', 'Class': 'Archaika', 'Magnitude': 0 },
  { 'Functional Group': 'Long-term Transport', 'Class': 'Defunctionalized', 'Magnitude': 3 },
  { 'Functional Group': 'Long-term Transport', 'Class': 'Miniatures', 'Magnitude': 0 },

  { 'Functional Group': 'Short-term Transport', 'Class': 'Local Mono Fine', 'Magnitude': 2 },
  { 'Functional Group': 'Short-term Transport', 'Class': 'Local Mono Coarse', 'Magnitude': 5 },
  { 'Functional Group': 'Short-term Transport', 'Class': 'Local Matt Painted', 'Magnitude': 1 },
  { 'Functional Group': 'Short-term Transport', 'Class': 'Local Impressed/Incised', 'Magnitude': 0 },
  { 'Functional Group': 'Short-term Transport', 'Class': 'Local Black Glazed', 'Magnitude': 0 },
  { 'Functional Group': 'Short-term Transport', 'Class': 'Regional Mono Fine', 'Magnitude': 0 },
  { 'Functional Group': 'Short-term Transport', 'Class': 'Regional Mono Coarse', 'Magnitude': 3 },
  { 'Functional Group': 'Short-term Transport', 'Class': 'Regional Matt Painted', 'Magnitude': 0 },
  { 'Functional Group': 'Short-term Transport', 'Class': 'Regional Impressed/Incised', 'Magnitude': 0 },
  { 'Functional Group': 'Short-term Transport', 'Class': 'Regional Black Glazed', 'Magnitude': 0 },
  { 'Functional Group': 'Short-term Transport', 'Class': 'Local/Regional Mono Fine', 'Magnitude': 0 },
  { 'Functional Group': 'Short-term Transport', 'Class': 'Local/Regional Mono Coarse', 'Magnitude': 3 },
  { 'Functional Group': 'Short-term Transport', 'Class': 'Local/Regional Matt Painted', 'Magnitude': 0 },
  { 'Functional Group': 'Short-term Transport', 'Class': 'Local/Regional Impressed/Incised', 'Magnitude': 0 },
  { 'Functional Group': 'Short-term Transport', 'Class': 'Local/Regional Black Glazed', 'Magnitude': 0 },
  { 'Functional Group': 'Short-term Transport', 'Class': 'Import Mono Fine', 'Magnitude': 0 },
  { 'Functional Group': 'Short-term Transport', 'Class': 'Import Mono Coarse', 'Magnitude': 3 },
  { 'Functional Group': 'Short-term Transport', 'Class': 'Import Matt Painted', 'Magnitude': 0 },
  { 'Functional Group': 'Short-term Transport', 'Class': 'Import Impressed/Incised', 'Magnitude': 0 },
  { 'Functional Group': 'Short-term Transport', 'Class': 'Import Black Glazed', 'Magnitude': 0 },
  { 'Functional Group': 'Short-term Transport', 'Class': 'Archaika', 'Magnitude': 0 },
  { 'Functional Group': 'Short-term Transport', 'Class': 'Defunctionalized', 'Magnitude': 3 },
  { 'Functional Group': 'Short-term Transport', 'Class': 'Miniatures', 'Magnitude': 0 },

  { 'Functional Group': 'Preparation/Cooking', 'Class': 'Local Mono Fine', 'Magnitude': 2 },
  { 'Functional Group': 'Preparation/Cooking', 'Class': 'Local Mono Coarse', 'Magnitude': 5 },
  { 'Functional Group': 'Preparation/Cooking', 'Class': 'Local Matt Painted', 'Magnitude': 1 },
  { 'Functional Group': 'Preparation/Cooking', 'Class': 'Local Impressed/Incised', 'Magnitude': 0 },
  { 'Functional Group': 'Preparation/Cooking', 'Class': 'Local Black Glazed', 'Magnitude': 0 },
  { 'Functional Group': 'Preparation/Cooking', 'Class': 'Regional Mono Fine', 'Magnitude': 0 },
  { 'Functional Group': 'Preparation/Cooking', 'Class': 'Regional Mono Coarse', 'Magnitude': 3 },
  { 'Functional Group': 'Preparation/Cooking', 'Class': 'Regional Matt Painted', 'Magnitude': 0 },
  { 'Functional Group': 'Preparation/Cooking', 'Class': 'Regional Impressed/Incised', 'Magnitude': 0 },
  { 'Functional Group': 'Preparation/Cooking', 'Class': 'Regional Black Glazed', 'Magnitude': 0 },
  { 'Functional Group': 'Preparation/Cooking', 'Class': 'Local/Regional Mono Fine', 'Magnitude': 0 },
  { 'Functional Group': 'Preparation/Cooking', 'Class': 'Local/Regional Mono Coarse', 'Magnitude': 3 },
  { 'Functional Group': 'Preparation/Cooking', 'Class': 'Local/Regional Matt Painted', 'Magnitude': 0 },
  { 'Functional Group': 'Preparation/Cooking', 'Class': 'Local/Regional Impressed/Incised', 'Magnitude': 0 },
  { 'Functional Group': 'Preparation/Cooking', 'Class': 'Local/Regional Black Glazed', 'Magnitude': 0 },
  { 'Functional Group': 'Preparation/Cooking', 'Class': 'Import Mono Fine', 'Magnitude': 0 },
  { 'Functional Group': 'Preparation/Cooking', 'Class': 'Import Mono Coarse', 'Magnitude': 3 },
  { 'Functional Group': 'Preparation/Cooking', 'Class': 'Import Matt Painted', 'Magnitude': 0 },
  { 'Functional Group': 'Preparation/Cooking', 'Class': 'Import Impressed/Incised', 'Magnitude': 0 },
  { 'Functional Group': 'Preparation/Cooking', 'Class': 'Import Black Glazed', 'Magnitude': 0 },
  { 'Functional Group': 'Preparation/Cooking', 'Class': 'Archaika', 'Magnitude': 0 },
  { 'Functional Group': 'Preparation/Cooking', 'Class': 'Defunctionalized', 'Magnitude': 3 },
  { 'Functional Group': 'Preparation/Cooking', 'Class': 'Miniatures', 'Magnitude': 0 },

  { 'Functional Group': 'Serving of Food', 'Class': 'Local Mono Fine', 'Magnitude': 2 },
  { 'Functional Group': 'Serving of Food', 'Class': 'Local Mono Coarse', 'Magnitude': 5 },
  { 'Functional Group': 'Serving of Food', 'Class': 'Local Matt Painted', 'Magnitude': 1 },
  { 'Functional Group': 'Serving of Food', 'Class': 'Local Impressed/Incised', 'Magnitude': 0 },
  { 'Functional Group': 'Serving of Food', 'Class': 'Local Black Glazed', 'Magnitude': 0 },
  { 'Functional Group': 'Serving of Food', 'Class': 'Regional Mono Fine', 'Magnitude': 0 },
  { 'Functional Group': 'Serving of Food', 'Class': 'Regional Mono Coarse', 'Magnitude': 3 },
  { 'Functional Group': 'Serving of Food', 'Class': 'Regional Matt Painted', 'Magnitude': 0 },
  { 'Functional Group': 'Serving of Food', 'Class': 'Regional Impressed/Incised', 'Magnitude': 0 },
  { 'Functional Group': 'Serving of Food', 'Class': 'Regional Black Glazed', 'Magnitude': 0 },
  { 'Functional Group': 'Serving of Food', 'Class': 'Local/Regional Mono Fine', 'Magnitude': 0 },
  { 'Functional Group': 'Serving of Food', 'Class': 'Local/Regional Mono Coarse', 'Magnitude': 3 },
  { 'Functional Group': 'Serving of Food', 'Class': 'Local/Regional Matt Painted', 'Magnitude': 0 },
  { 'Functional Group': 'Serving of Food', 'Class': 'Local/Regional Impressed/Incised', 'Magnitude': 0 },
  { 'Functional Group': 'Serving of Food', 'Class': 'Local/Regional Black Glazed', 'Magnitude': 0 },
  { 'Functional Group': 'Serving of Food', 'Class': 'Import Mono Fine', 'Magnitude': 0 },
  { 'Functional Group': 'Serving of Food', 'Class': 'Import Mono Coarse', 'Magnitude': 3 },
  { 'Functional Group': 'Serving of Food', 'Class': 'Import Matt Painted', 'Magnitude': 0 },
  { 'Functional Group': 'Serving of Food', 'Class': 'Import Impressed/Incised', 'Magnitude': 0 },
  { 'Functional Group': 'Serving of Food', 'Class': 'Import Black Glazed', 'Magnitude': 0 },
  { 'Functional Group': 'Serving of Food', 'Class': 'Archaika', 'Magnitude': 0 },
  { 'Functional Group': 'Serving of Food', 'Class': 'Defunctionalized', 'Magnitude': 3 },
  { 'Functional Group': 'Serving of Food', 'Class': 'Miniatures', 'Magnitude': 0 },

  { 'Functional Group': 'Mixing of Drinks', 'Class': 'Local Mono Fine', 'Magnitude': 2 },
  { 'Functional Group': 'Mixing of Drinks', 'Class': 'Local Mono Coarse', 'Magnitude': 5 },
  { 'Functional Group': 'Mixing of Drinks', 'Class': 'Local Matt Painted', 'Magnitude': 1 },
  { 'Functional Group': 'Mixing of Drinks', 'Class': 'Local Impressed/Incised', 'Magnitude': 0 },
  { 'Functional Group': 'Mixing of Drinks', 'Class': 'Local Black Glazed', 'Magnitude': 0 },
  { 'Functional Group': 'Mixing of Drinks', 'Class': 'Regional Mono Fine', 'Magnitude': 0 },
  { 'Functional Group': 'Mixing of Drinks', 'Class': 'Regional Mono Coarse', 'Magnitude': 3 },
  { 'Functional Group': 'Mixing of Drinks', 'Class': 'Regional Matt Painted', 'Magnitude': 0 },
  { 'Functional Group': 'Mixing of Drinks', 'Class': 'Regional Impressed/Incised', 'Magnitude': 0 },
  { 'Functional Group': 'Mixing of Drinks', 'Class': 'Regional Black Glazed', 'Magnitude': 0 },
  { 'Functional Group': 'Mixing of Drinks', 'Class': 'Local/Regional Mono Fine', 'Magnitude': 0 },
  { 'Functional Group': 'Mixing of Drinks', 'Class': 'Local/Regional Mono Coarse', 'Magnitude': 3 },
  { 'Functional Group': 'Mixing of Drinks', 'Class': 'Local/Regional Matt Painted', 'Magnitude': 0 },
  { 'Functional Group': 'Mixing of Drinks', 'Class': 'Local/Regional Impressed/Incised', 'Magnitude': 0 },
  { 'Functional Group': 'Mixing of Drinks', 'Class': 'Local/Regional Black Glazed', 'Magnitude': 0 },
  { 'Functional Group': 'Mixing of Drinks', 'Class': 'Import Mono Fine', 'Magnitude': 0 },
  { 'Functional Group': 'Mixing of Drinks', 'Class': 'Import Mono Coarse', 'Magnitude': 3 },
  { 'Functional Group': 'Mixing of Drinks', 'Class': 'Import Matt Painted', 'Magnitude': 0 },
  { 'Functional Group': 'Mixing of Drinks', 'Class': 'Import Impressed/Incised', 'Magnitude': 0 },
  { 'Functional Group': 'Mixing of Drinks', 'Class': 'Import Black Glazed', 'Magnitude': 0 },
  { 'Functional Group': 'Mixing of Drinks', 'Class': 'Archaika', 'Magnitude': 0 },
  { 'Functional Group': 'Mixing of Drinks', 'Class': 'Defunctionalized', 'Magnitude': 3 },
  { 'Functional Group': 'Mixing of Drinks', 'Class': 'Miniatures', 'Magnitude': 0 },

  { 'Functional Group': 'Serving of Drinks', 'Class': 'Local Mono Fine', 'Magnitude': 2 },
  { 'Functional Group': 'Serving of Drinks', 'Class': 'Local Mono Coarse', 'Magnitude': 5 },
  { 'Functional Group': 'Serving of Drinks', 'Class': 'Local Matt Painted', 'Magnitude': 1 },
  { 'Functional Group': 'Serving of Drinks', 'Class': 'Local Impressed/Incised', 'Magnitude': 0 },
  { 'Functional Group': 'Serving of Drinks', 'Class': 'Local Black Glazed', 'Magnitude': 0 },
  { 'Functional Group': 'Serving of Drinks', 'Class': 'Regional Mono Fine', 'Magnitude': 0 },
  { 'Functional Group': 'Serving of Drinks', 'Class': 'Regional Mono Coarse', 'Magnitude': 3 },
  { 'Functional Group': 'Serving of Drinks', 'Class': 'Regional Matt Painted', 'Magnitude': 0 },
  { 'Functional Group': 'Serving of Drinks', 'Class': 'Regional Impressed/Incised', 'Magnitude': 0 },
  { 'Functional Group': 'Serving of Drinks', 'Class': 'Regional Black Glazed', 'Magnitude': 0 },
  { 'Functional Group': 'Serving of Drinks', 'Class': 'Local/Regional Mono Fine', 'Magnitude': 0 },
  { 'Functional Group': 'Serving of Drinks', 'Class': 'Local/Regional Mono Coarse', 'Magnitude': 3 },
  { 'Functional Group': 'Serving of Drinks', 'Class': 'Local/Regional Matt Painted', 'Magnitude': 0 },
  { 'Functional Group': 'Serving of Drinks', 'Class': 'Local/Regional Impressed/Incised', 'Magnitude': 0 },
  { 'Functional Group': 'Serving of Drinks', 'Class': 'Local/Regional Black Glazed', 'Magnitude': 0 },
  { 'Functional Group': 'Serving of Drinks', 'Class': 'Import Mono Fine', 'Magnitude': 0 },
  { 'Functional Group': 'Serving of Drinks', 'Class': 'Import Mono Coarse', 'Magnitude': 3 },
  { 'Functional Group': 'Serving of Drinks', 'Class': 'Import Matt Painted', 'Magnitude': 0 },
  { 'Functional Group': 'Serving of Drinks', 'Class': 'Import Impressed/Incised', 'Magnitude': 0 },
  { 'Functional Group': 'Serving of Drinks', 'Class': 'Import Black Glazed', 'Magnitude': 0 },
  { 'Functional Group': 'Serving of Drinks', 'Class': 'Archaika', 'Magnitude': 0 },
  { 'Functional Group': 'Serving of Drinks', 'Class': 'Defunctionalized', 'Magnitude': 3 },
  { 'Functional Group': 'Serving of Drinks', 'Class': 'Miniatures', 'Magnitude': 0 },

  { 'Functional Group': 'Consumption of Drinks', 'Class': 'Local Mono Fine', 'Magnitude': 2 },
  { 'Functional Group': 'Consumption of Drinks', 'Class': 'Local Mono Coarse', 'Magnitude': 5 },
  { 'Functional Group': 'Consumption of Drinks', 'Class': 'Local Matt Painted', 'Magnitude': 1 },
  { 'Functional Group': 'Consumption of Drinks', 'Class': 'Local Impressed/Incised', 'Magnitude': 0 },
  { 'Functional Group': 'Consumption of Drinks', 'Class': 'Local Black Glazed', 'Magnitude': 0 },
  { 'Functional Group': 'Consumption of Drinks', 'Class': 'Regional Mono Fine', 'Magnitude': 0 },
  { 'Functional Group': 'Consumption of Drinks', 'Class': 'Regional Mono Coarse', 'Magnitude': 3 },
  { 'Functional Group': 'Consumption of Drinks', 'Class': 'Regional Matt Painted', 'Magnitude': 0 },
  { 'Functional Group': 'Consumption of Drinks', 'Class': 'Regional Impressed/Incised', 'Magnitude': 0 },
  { 'Functional Group': 'Consumption of Drinks', 'Class': 'Regional Black Glazed', 'Magnitude': 0 },
  { 'Functional Group': 'Consumption of Drinks', 'Class': 'Local/Regional Mono Fine', 'Magnitude': 0 },
  { 'Functional Group': 'Consumption of Drinks', 'Class': 'Local/Regional Mono Coarse', 'Magnitude': 3 },
  { 'Functional Group': 'Consumption of Drinks', 'Class': 'Local/Regional Matt Painted', 'Magnitude': 0 },
  { 'Functional Group': 'Consumption of Drinks', 'Class': 'Local/Regional Impressed/Incised', 'Magnitude': 0 },
  { 'Functional Group': 'Consumption of Drinks', 'Class': 'Local/Regional Black Glazed', 'Magnitude': 0 },
  { 'Functional Group': 'Consumption of Drinks', 'Class': 'Import Mono Fine', 'Magnitude': 0 },
  { 'Functional Group': 'Consumption of Drinks', 'Class': 'Import Mono Coarse', 'Magnitude': 3 },
  { 'Functional Group': 'Consumption of Drinks', 'Class': 'Import Matt Painted', 'Magnitude': 0 },
  { 'Functional Group': 'Consumption of Drinks', 'Class': 'Import Impressed/Incised', 'Magnitude': 0 },
  { 'Functional Group': 'Consumption of Drinks', 'Class': 'Import Black Glazed', 'Magnitude': 0 },
  { 'Functional Group': 'Consumption of Drinks', 'Class': 'Archaika', 'Magnitude': 0 },
  { 'Functional Group': 'Consumption of Drinks', 'Class': 'Defunctionalized', 'Magnitude': 3 },
  { 'Functional Group': 'Consumption of Drinks', 'Class': 'Miniatures', 'Magnitude': 0 },

  { 'Functional Group': 'Perfumes and Fragrances', 'Class': 'Local Mono Fine', 'Magnitude': 2 },
  { 'Functional Group': 'Perfumes and Fragrances', 'Class': 'Local Mono Coarse', 'Magnitude': 5 },
  { 'Functional Group': 'Perfumes and Fragrances', 'Class': 'Local Matt Painted', 'Magnitude': 1 },
  { 'Functional Group': 'Perfumes and Fragrances', 'Class': 'Local Impressed/Incised', 'Magnitude': 0 },
  { 'Functional Group': 'Perfumes and Fragrances', 'Class': 'Local Black Glazed', 'Magnitude': 0 },
  { 'Functional Group': 'Perfumes and Fragrances', 'Class': 'Regional Mono Fine', 'Magnitude': 0 },
  { 'Functional Group': 'Perfumes and Fragrances', 'Class': 'Regional Mono Coarse', 'Magnitude': 3 },
  { 'Functional Group': 'Perfumes and Fragrances', 'Class': 'Regional Matt Painted', 'Magnitude': 0 },
  { 'Functional Group': 'Perfumes and Fragrances', 'Class': 'Regional Impressed/Incised', 'Magnitude': 0 },
  { 'Functional Group': 'Perfumes and Fragrances', 'Class': 'Regional Black Glazed', 'Magnitude': 0 },
  { 'Functional Group': 'Perfumes and Fragrances', 'Class': 'Local/Regional Mono Fine', 'Magnitude': 0 },
  { 'Functional Group': 'Perfumes and Fragrances', 'Class': 'Local/Regional Mono Coarse', 'Magnitude': 3 },
  { 'Functional Group': 'Perfumes and Fragrances', 'Class': 'Local/Regional Matt Painted', 'Magnitude': 0 },
  { 'Functional Group': 'Perfumes and Fragrances', 'Class': 'Local/Regional Impressed/Incised', 'Magnitude': 0 },
  { 'Functional Group': 'Perfumes and Fragrances', 'Class': 'Local/Regional Black Glazed', 'Magnitude': 0 },
  { 'Functional Group': 'Perfumes and Fragrances', 'Class': 'Import Mono Fine', 'Magnitude': 0 },
  { 'Functional Group': 'Perfumes and Fragrances', 'Class': 'Import Mono Coarse', 'Magnitude': 3 },
  { 'Functional Group': 'Perfumes and Fragrances', 'Class': 'Import Matt Painted', 'Magnitude': 0 },
  { 'Functional Group': 'Perfumes and Fragrances', 'Class': 'Import Impressed/Incised', 'Magnitude': 0 },
  { 'Functional Group': 'Perfumes and Fragrances', 'Class': 'Import Black Glazed', 'Magnitude': 0 },
  { 'Functional Group': 'Perfumes and Fragrances', 'Class': 'Archaika', 'Magnitude': 0 },
  { 'Functional Group': 'Perfumes and Fragrances', 'Class': 'Defunctionalized', 'Magnitude': 3 },
  { 'Functional Group': 'Perfumes and Fragrances', 'Class': 'Miniatures', 'Magnitude': 0 },

  { 'Functional Group': 'Light', 'Class': 'Local Mono Fine', 'Magnitude': 2 },
  { 'Functional Group': 'Light', 'Class': 'Local Mono Coarse', 'Magnitude': 5 },
  { 'Functional Group': 'Light', 'Class': 'Local Matt Painted', 'Magnitude': 1 },
  { 'Functional Group': 'Light', 'Class': 'Local Impressed/Incised', 'Magnitude': 0 },
  { 'Functional Group': 'Light', 'Class': 'Local Black Glazed', 'Magnitude': 0 },
  { 'Functional Group': 'Light', 'Class': 'Regional Mono Fine', 'Magnitude': 0 },
  { 'Functional Group': 'Light', 'Class': 'Regional Mono Coarse', 'Magnitude': 3 },
  { 'Functional Group': 'Light', 'Class': 'Regional Matt Painted', 'Magnitude': 0 },
  { 'Functional Group': 'Light', 'Class': 'Regional Impressed/Incised', 'Magnitude': 0 },
  { 'Functional Group': 'Light', 'Class': 'Regional Black Glazed', 'Magnitude': 0 },
  { 'Functional Group': 'Light', 'Class': 'Local/Regional Mono Fine', 'Magnitude': 0 },
  { 'Functional Group': 'Light', 'Class': 'Local/Regional Mono Coarse', 'Magnitude': 3 },
  { 'Functional Group': 'Light', 'Class': 'Local/Regional Matt Painted', 'Magnitude': 0 },
  { 'Functional Group': 'Light', 'Class': 'Local/Regional Impressed/Incised', 'Magnitude': 0 },
  { 'Functional Group': 'Light', 'Class': 'Local/Regional Black Glazed', 'Magnitude': 0 },
  { 'Functional Group': 'Light', 'Class': 'Import Mono Fine', 'Magnitude': 0 },
  { 'Functional Group': 'Light', 'Class': 'Import Mono Coarse', 'Magnitude': 3 },
  { 'Functional Group': 'Light', 'Class': 'Import Matt Painted', 'Magnitude': 0 },
  { 'Functional Group': 'Light', 'Class': 'Import Impressed/Incised', 'Magnitude': 0 },
  { 'Functional Group': 'Light', 'Class': 'Import Black Glazed', 'Magnitude': 0 },
  { 'Functional Group': 'Light', 'Class': 'Archaika', 'Magnitude': 0 },
  { 'Functional Group': 'Light', 'Class': 'Defunctionalized', 'Magnitude': 3 },
  { 'Functional Group': 'Light', 'Class': 'Miniatures', 'Magnitude': 0 },

  { 'Functional Group': 'Storage of non-edibles', 'Class': 'Local Mono Fine', 'Magnitude': 2 },
  { 'Functional Group': 'Storage of non-edibles', 'Class': 'Local Mono Coarse', 'Magnitude': 5 },
  { 'Functional Group': 'Storage of non-edibles', 'Class': 'Local Matt Painted', 'Magnitude': 1 },
  { 'Functional Group': 'Storage of non-edibles', 'Class': 'Local Impressed/Incised', 'Magnitude': 0 },
  { 'Functional Group': 'Storage of non-edibles', 'Class': 'Local Black Glazed', 'Magnitude': 0 },
  { 'Functional Group': 'Storage of non-edibles', 'Class': 'Regional Mono Fine', 'Magnitude': 0 },
  { 'Functional Group': 'Storage of non-edibles', 'Class': 'Regional Mono Coarse', 'Magnitude': 3 },
  { 'Functional Group': 'Storage of non-edibles', 'Class': 'Regional Matt Painted', 'Magnitude': 0 },
  { 'Functional Group': 'Storage of non-edibles', 'Class': 'Regional Impressed/Incised', 'Magnitude': 0 },
  { 'Functional Group': 'Storage of non-edibles', 'Class': 'Regional Black Glazed', 'Magnitude': 0 },
  { 'Functional Group': 'Storage of non-edibles', 'Class': 'Local/Regional Mono Fine', 'Magnitude': 0 },
  { 'Functional Group': 'Storage of non-edibles', 'Class': 'Local/Regional Mono Coarse', 'Magnitude': 3 },
  { 'Functional Group': 'Storage of non-edibles', 'Class': 'Local/Regional Matt Painted', 'Magnitude': 0 },
  { 'Functional Group': 'Storage of non-edibles', 'Class': 'Local/Regional Impressed/Incised', 'Magnitude': 0 },
  { 'Functional Group': 'Storage of non-edibles', 'Class': 'Local/Regional Black Glazed', 'Magnitude': 0 },
  { 'Functional Group': 'Storage of non-edibles', 'Class': 'Import Mono Fine', 'Magnitude': 0 },
  { 'Functional Group': 'Storage of non-edibles', 'Class': 'Import Mono Coarse', 'Magnitude': 3 },
  { 'Functional Group': 'Storage of non-edibles', 'Class': 'Import Matt Painted', 'Magnitude': 0 },
  { 'Functional Group': 'Storage of non-edibles', 'Class': 'Import Impressed/Incised', 'Magnitude': 0 },
  { 'Functional Group': 'Storage of non-edibles', 'Class': 'Import Black Glazed', 'Magnitude': 0 },
  { 'Functional Group': 'Storage of non-edibles', 'Class': 'Archaika', 'Magnitude': 0 },
  { 'Functional Group': 'Storage of non-edibles', 'Class': 'Defunctionalized', 'Magnitude': 3 },
  { 'Functional Group': 'Storage of non-edibles', 'Class': 'Miniatures', 'Magnitude': 0 },

  { 'Functional Group': 'Unidentified', 'Class': 'Local Mono Fine', 'Magnitude': 2 },
  { 'Functional Group': 'Unidentified', 'Class': 'Local Mono Coarse', 'Magnitude': 5 },
  { 'Functional Group': 'Unidentified', 'Class': 'Local Matt Painted', 'Magnitude': 1 },
  { 'Functional Group': 'Unidentified', 'Class': 'Local Impressed/Incised', 'Magnitude': 0 },
  { 'Functional Group': 'Unidentified', 'Class': 'Local Black Glazed', 'Magnitude': 0 },
  { 'Functional Group': 'Unidentified', 'Class': 'Regional Mono Fine', 'Magnitude': 0 },
  { 'Functional Group': 'Unidentified', 'Class': 'Regional Mono Coarse', 'Magnitude': 3 },
  { 'Functional Group': 'Unidentified', 'Class': 'Regional Matt Painted', 'Magnitude': 0 },
  { 'Functional Group': 'Unidentified', 'Class': 'Regional Impressed/Incised', 'Magnitude': 0 },
  { 'Functional Group': 'Unidentified', 'Class': 'Regional Black Glazed', 'Magnitude': 0 },
  { 'Functional Group': 'Unidentified', 'Class': 'Local/Regional Mono Fine', 'Magnitude': 0 },
  { 'Functional Group': 'Unidentified', 'Class': 'Local/Regional Mono Coarse', 'Magnitude': 3 },
  { 'Functional Group': 'Unidentified', 'Class': 'Local/Regional Matt Painted', 'Magnitude': 0 },
  { 'Functional Group': 'Unidentified', 'Class': 'Local/Regional Impressed/Incised', 'Magnitude': 0 },
  { 'Functional Group': 'Unidentified', 'Class': 'Local/Regional Black Glazed', 'Magnitude': 0 },
  { 'Functional Group': 'Unidentified', 'Class': 'Import Mono Fine', 'Magnitude': 0 },
  { 'Functional Group': 'Unidentified', 'Class': 'Import Mono Coarse', 'Magnitude': 3 },
  { 'Functional Group': 'Unidentified', 'Class': 'Import Matt Painted', 'Magnitude': 0 },
  { 'Functional Group': 'Unidentified', 'Class': 'Import Impressed/Incised', 'Magnitude': 0 },
  { 'Functional Group': 'Unidentified', 'Class': 'Import Black Glazed', 'Magnitude': 0 },
  { 'Functional Group': 'Unidentified', 'Class': 'Archaika', 'Magnitude': 0 },
  { 'Functional Group': 'Unidentified', 'Class': 'Defunctionalized', 'Magnitude': 3 },
  { 'Functional Group': 'Unidentified', 'Class': 'Miniatures', 'Magnitude': 0 }
];
